baseURL: "https://xuexixiaozhushou.github.io/"
theme: "up-business-theme"
languageCode: "en-us"
publishDir: "docs"

title: ""

# googleAnalytics: ""

summaryLength: 20

params:
  title: "学习小助手"
  description: "你的学习之路，我们一路相伴！"
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "北京朝阳区泰康金融大厦55F"

  contact:
    - "xuexixiaozhushou@163.com"
    # - "207.555.0119"

  copyright: "Copyright © 2021. All Rights Reserved."

  postProcess: false

menus:
  main:
    - name: "首页"
      url: "/#hero"
      weight: 1

    - name: "下载"
      url: "/#"
      weight: 2

    - name: "帮助中心"
      url: "/#"
      weight: 3

    - name: "隐私协议"
      url: "/#"
      weight: 4

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

  # buttons:
  #   - name: "立刻下载"
  #     url: "/#"
  #     weight: 5
  #     pre: "btn btn-primary text-light"

  footer:
    # - name: "首页"
    #   url: "/#hero"
    #   weight: 1

    - name: "用户协议"
      url: "/#"
      weight: 2

    - name: "知识产权声明"
      url: "/#"
      weight: 3

    - name: "隐私政策"
      url: "/#"
      weight: 4

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

taxonomies:
  series: "series"
  tags: "tags"
